# Generated by Django 3.1.3 on 2020-11-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field=370, null=True, upload_to='', width_field=300),
        ),
    ]
