# Generated by Django 3.1.3 on 2020-11-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theshop', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
